server:
   port: ${PORT:9080}
application:
   name: gateway
   description: Gateway
   version: 1.0.0-SNAPSHOT
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:8761}/eureka/}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes: # these are samples
      - id: loan-application-service
        uri: lb://loan-application-service
        predicates:
        - Path=/api/loanapplications/**
      - id: customer-service
        uri: lb://customer-service
        predicates:
        - Path=/**
  
 
      