server:
  port: ${PORT:8761}
application:
  name: eureka
  description: Eureka
  version: 1.0.0-SNAPSHOT
spring:
  application:
    name: eureka
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/